include: package:lints/recommended.yaml

linter:
  rules:
    - camel_case_types
    - comment_references
    - dangling_library_doc_comments
    - public_member_api_docs
    - slash_for_doc_comments
    - unnecessary_library_directive
    - require_trailing_commas

analyzer:
  errors:
    invalid_annotation_target: ignore
