name: televerse
description: Televerse lets you create your own efficient Telegram bots with ease in Dart. Supports latest Telegram Bot API - 8.3!
version: 2.4.4
homepage: https://televerse.xooniverse.com
repository: https://github.com/xooniverse/televerse
topics:
  - telegram
  - bot
  - chat
  - telegram-bot-api
  - bot-framework

funding:
  - https://buymeacoffee.com/heysreelal

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  lints: ^4.0.0
  test: ^1.25.0
