name: televerse
description: Televerse lets you create your own efficient Telegram bots with ease in Dart. Supports latest Telegram Bot API - 7.10!
version: 1.26.4
homepage: https://televerse.xooniverse.com
repository: https://github.com/xooniverse/televerse
topics:
  - telegram
  - bot
  - chat
  - telegram-bot-api
  - bot-framework

funding:
  - https://buymeacoffee.com/heysreelal

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
